name: stock_take
description: "Standard Stock Taking Application"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1  #Need to update for version management

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  cupertino_icons: ^1.0.2
  path: ^1.8.3
  google_fonts: ^6.1.0
  file_picker: ^6.1.1
  csv: ^5.1.1
  intl: ^0.18.1
  reorderables: ^0.6.0
  permission_handler: ^11.1.0
  flutter_barcode_scanner: ^2.0.0
  external_path: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/api.jpg

fonts:
  - family: Oswald
    fonts:
      - asset: fonts/Oswald-Medium.ttf

  - family: PortLligatSans
    fonts:
      - asset: fonts/PortLligatSans-Regular.ttf

  - family: Lato
    fonts:
      - asset: fonts/Lato-Regular.ttf